### ISSUE TITLE
taroApp是undefined

### ISSUE THREAD

**Issue by zhiyingzzhou** [NervJS/taro-blended#2]
![image](https://user-images.githubusercontent.com/16408285/106129218-02384780-619b-11eb-9360-ee1d98769e6a.png)
![image](https://user-images.githubusercontent.com/16408285/106129241-082e2880-619b-11eb-8249-4392f6808838.png)

**Comment by Chen-jj** [comment]
看看 `./taro/app.js` 的代码

**Comment by zhiyingzzhou** [comment]
> 看看 `./taro/app.js` 的代码

require("./runtime"), require("./common"), require("./vendors"), require("./taro"), (wx["webpackJsonp"] = wx["webpackJsonp"] || []).push([
    [5], {
        39: function (e, n, o) {},
        43: function (e, n, o) {
            "use strict";
            o.r(n);
            var t = o(2),
                a = o(0),
                i = o(1),
                r = o(5),
                c = o(6),
                p = o(4),
                u = (o(39), function (e) {
                    Object(r["a"])(o, e);
                    var n = Object(c["a"])(o);

                    function o() {
                        return Object(a["a"])(this, o), n.apply(this, arguments)
                    }
                    return Object(i["a"])(o, [{
                        key: "componentDidMount",
                        value: function () {
                            console.log("app launch")
                        }
                    }, {
                        key: "componentDidShow",
                        value: function () {
                            console.log("app show")
                        }
                    }, {
                        key: "componentDidHide",
                        value: function () {
                            console.log("app hide")
                        }
                    }, {
                        key: "componentDidCatchError",
                        value: function () {}
                    }, {
                        key: "render",
                        value: function () {
                            return this.props.children
                        }
                    }]), o
                }(p["Component"])),
                l = u,
                s = o(29),
                d = {
                    pages: ["pages/index/index", "subpackages/bar/index", "subpackages/foo/index"],
                    window: {
                        backgroundTextStyle: "light",
                        navigationBarBackgroundColor: "#fff",
                        navigationBarTitleText: "WeChat",
                        navigationBarTextStyle: "black"
                    }
                };
            t["window"].__taroAppConfig = d;
            App(Object(t["createReactApp"])(l, p, s["a"], d))
        }
    },
    [
        [43, 0, 1, 2]
    ]
]);

**Comment by Chen-jj** [comment]
@zhiyingzzhou taro 相关依赖更新到 3.0.25 再试试

**Comment by Chen-jj** [comment]
这里在 `blended` 下不应该调用 `App` 构造器：

>  App(Object(t["createReactApp"])(l, p, s["a"], d))

而是：

![image](https://user-images.githubusercontent.com/11807297/106239226-32d0bd80-623d-11eb-85b0-0b39c220f856.png)

taro 3.0.25+ 才支持，已更新此项目的 package.json

**Comment by zhiyingzzhou** [comment]
> 这里在 `blended` 下不应该调用 `App` 构造器：
> 
> > App(Object(t["createReactApp"])(l, p, s["a"], d))
> 
> 而是：
> 
> ![image](https://user-images.githubusercontent.com/11807297/106239226-32d0bd80-623d-11eb-85b0-0b39c220f856.png)
> 
> taro 3.0.25+ 才支持，已更新此项目的 package.json

可以了 多谢了👍👍
