### ISSUE TITLE
引用原生项目的 JS 文件路径报错

### ISSUE THREAD

**Issue by HUYIJUNCODING** [NervJS/taro-blended#3]
1. taro build --type weapp --blended
2. 微信开发者工具中导入项目
3. 报错
![微信图片_20210131234142](https://user-images.githubusercontent.com/33798719/106389397-efd72d00-6397-11eb-9b62-094eb5b4ddc6.png)
![微信图片_20210131234150](https://user-images.githubusercontent.com/33798719/106389400-f4034a80-6397-11eb-8721-0d2d22a2e817.png)

**Comment by Chen-jj** [comment]
应该是对 windows 的路径处理有问题，我们看看

**Comment by HUYIJUNCODING** [comment]
@Chen-jj 我用 replace 方法再次替换了一下,但是发现打包后的路径其实还是有问题的,不同组件下引用相同的js文件,那么编译后生成的相对路径层级相同,这有问题,麻烦看哈,谢谢

**Comment by Chen-jj** [comment]
@HUYIJUNCODING Windows 中把 `path.resolve` 里的 `/` 都改成 `\` 应该就行了：

![image](https://user-images.githubusercontent.com/11807297/107377945-791ff980-6b26-11eb-8c2a-112ccb998dfe.png)

> 但是发现打包后的路径其实还是有问题的,不同组件下引用相同的js文件,那么编译后生成的相对路径层级相同,这有问题

另外这点没看懂

**Comment by HUYIJUNCODING** [comment]
就是在a,b 两个不同的组件(两个组件的目录层级深度不同)下引用相同原生项目的 JS 文件,会发现编译后的js文件相对路径测层级是相同的(比如,a组件下编译后应该是../../xxx,b组件下编译后应该是../../../xxx),但是实际情况都是../../xxx这样的相对路径

**Comment by andychenminiso** [comment]
![image](https://user-images.githubusercontent.com/92304265/137426827-106e6cbb-f5e9-4559-81dc-0075642e313a.png)
在这里转一下就行

**Comment by ChenAnDing** [comment]
![image](https://user-images.githubusercontent.com/24455594/137427023-024119ff-8a43-476e-8577-873bc91da8d1.png)
打包的时候转一下就行
