### ISSUE TITLE
taro build --type weapp --watch --blended引用出错

### ISSUE THREAD

**Issue by vinurs** [NervJS/taro-blended#7]
`taro build --type weapp --watch --blended`
![image](https://user-images.githubusercontent.com/37489300/114003461-55f89880-9890-11eb-8bd5-905614dcca4f.png)
不用watch直接编译的时候是可以的

**Comment by Chen-jj** [comment]
如果是一个完整的 Taro 项目作为一个分包，watch 时开发者工具启动的是 Taro 项目根目录，生产时启动的是原生项目根目录

**Comment by vinurs** [comment]
那这个示例项目中我该咋做？我试了一下开发者工具导入taro-project，但是不行
![image](https://user-images.githubusercontent.com/37489300/114096416-4198b800-98f1-11eb-944d-ebe739203efb.png)

**Comment by linguoqiang001** [comment]
taro build --type weapp --watch --blended
![image](https://user-images.githubusercontent.com/20842435/123910783-83e00b80-d9ad-11eb-8e93-1ef607e82434.png)
watch下有问题

**Comment by vinurs** [comment]
@linguoqiang001 开发的时候开发者工具打开taro-project目录就可以了，不要打开miniapp目录
